language: python

branches:
  only:
  - master
  - develop

jobs:
  include:
    - os: linux
      dist: trusty

python:
  - '3.7'

sudo: true

before_install:
  - ./setup.sh

script: 
- cd code 
- pytest
